# Generated by Django 5.1.7 on 2025-04-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_add_email_and_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="poster_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
